import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { cn } from "@/lib/utils";


const myFont = localFont({
  src: '../public/fonts/font.ttf',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'tweeter',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", "dark", "font-sans", myFont.className)}>
      <body
        className={`${myFont.className} flex flex-col min-h-full dark root`}
        cz-shortcut-listen="false"
      >
        {children}
      </body>
    </html>
  );
}