import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const myFont = localFont({
  src: '../public/fonts/font.ttf',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'tweeter',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased dark`}>
      <body
        className={`${myFont.className} flex flex-col min-h-full dark `}
        cz-shortcut-listen="false"
      >
        {children}
      </body>
    </html>
  );
}
